// Article source. Each section has a stable ID, Japanese title/body, English title/body.
export const groups = [['start','はじめる','Getting started'],['edit','編集する','Editing'],['reference','調べる','Reference']];
export const pages = [];
const page = (id, group, ja, en, introJa, introEn, sections) => pages.push({id, group, ja, en, introJa, introEn, sections});

page('index','start','OMMTの使い方','OMMT handbook',
'MIDIやNBSを読み込み、Minecraftの音で確かめながら編集して、おやさいサーバーへ送るためのガイドです。',
'Import a MIDI or NBS song, edit it with Minecraft sounds, and send a draft to the Oyasai Server.',[
['start','初めて使う方へ',`<p>OMMTは<strong>おやさいサーバー専用のクライアントMOD</strong>です。編集と試聴は手元で行い、「下書き送信」を押すとサーバーへ曲を送ります。</p><ol class="reading-list"><li><a href="install.html">OMMTを導入する</a><span>必要なMODを揃えて、編集画面を開く。</span></li><li><a href="first-song.html">最初の1曲を送る</a><span>ファイルを読み込み、1か所編集して、保存・送信する。</span></li><li><a href="editing.html">ノートを編集する</a><span>選ぶ、動かす、長さを変える。</span></li></ol>`,
'New to OMMT?',`<p>OMMT is a <strong>client mod made for the Oyasai Server</strong>. Editing and preview happen locally. Upload a draft when you are ready to send your song.</p><ol class="reading-list"><li><a href="install-en.html">Install OMMT</a><span>Install the required mods and open the editor.</span></li><li><a href="first-song-en.html">Send your first song</a><span>Import, make one edit, save, then upload.</span></li><li><a href="editing-en.html">Edit notes</a><span>Select, move, and resize notes.</span></li></ol>`],
['find','やりたいことから探す',`<ul class="link-list"><li><a href="parts.html">主旋律と伴奏を分けたい</a></li><li><a href="sound.html">楽器やMinecraftサウンドを変えたい</a></li><li><a href="volume-pan.html">伴奏を小さくしたい・左右に音を振りたい</a></li><li><a href="tempo.html">曲の途中で速さを変えたい</a></li><li><a href="release.html">長い音に減衰を付けたい</a></li><li><a href="save-upload.html">編集の続きを再開したい</a></li></ul>`,
'Find a task',`<ul class="link-list"><li><a href="parts-en.html">Separate melody and accompaniment</a></li><li><a href="sound-en.html">Change an instrument or Minecraft sound</a></li><li><a href="volume-pan-en.html">Balance volume and stereo position</a></li><li><a href="tempo-en.html">Change tempo during a song</a></li><li><a href="release-en.html">Add a fading tail to long notes</a></li><li><a href="save-upload-en.html">Resume a saved project</a></li></ul>`],
['about','このガイドについて',`<p>Minecraft 26.2向けの現在のOMMTを説明しています。操作キーは初期設定です。変更している場合は、OMMTの「設定 → キーマップ」を優先してください。</p><p>分からない言葉は<a href="glossary.html">用語集</a>、操作がうまくいかない場合は<a href="help.html">困ったとき</a>へ。上部の検索では「音が出ない」「パート移動」のような言葉でも探せます。</p>`,
'About this guide',`<p>This handbook covers the current Minecraft 26.2 version. Keyboard shortcuts assume default bindings; your editor keymap takes precedence if you have changed them.</p><p>Use the <a href="glossary-en.html">glossary</a> for unfamiliar terms and <a href="help-en.html">troubleshooting</a> when something goes wrong. Search finds article headings and text, not just page titles.</p>`]
]);

page('install','start','導入と最初の起動','Install and open OMMT','MinecraftとMODの対応バージョンを揃えてから、編集画面を開きます。','Match your Minecraft and mod versions, then open the editor.',[
['requirements','必要なもの',`<p>現在の対象は<strong>Minecraft Java Edition 26.2 / Fabric</strong>です。統合版にOMMTを入れることはできません。</p><ul><li>OMMT（26.2用のJAR）</li><li>Fabric Loader</li><li>Fabric API</li><li>Fabric Language Kotlin</li><li>Fabric GUI ImGui</li></ul><p>配布ページの依存関係に合わせた版を使ってください。Minecraft 1.21.11・26.1.2向けの旧JARとは混在させません。Modrinth Appなどで入れる場合も、前提MODが揃っているか確認します。</p>`,
'Requirements',`<p>The maintained target is <strong>Minecraft Java Edition 26.2 with Fabric</strong>. OMMT cannot be installed on Bedrock Edition.</p><ul><li>OMMT JAR for 26.2</li><li>Fabric Loader</li><li>Fabric API</li><li>Fabric Language Kotlin</li><li>Fabric GUI ImGui</li></ul><p>Use the dependency versions listed with your OMMT release. Do not mix older 1.21.11 or 26.1.2 builds into this profile. Check dependencies even when installing with a launcher.</p>`],
['open','編集画面を開く',`<ol><li>使うランチャーの26.2プロファイルへMODを入れ、Minecraftを起動します。</li><li>ワールドへ入り、<kbd>O</kbd>を押します。</li><li>OMMTのライブラリとピアノロールが見えれば起動できています。</li></ol><p>開かない場合はMinecraftの「設定 → 操作設定 → キー割り当て」でOMMTを探してください。他のMODと同じキーなら、重ならないキーに変更します。</p>`,
'Open the editor',`<ol><li>Install the mods in your launcher’s 26.2 profile and start Minecraft.</li><li>Enter a world and press <kbd>O</kbd>.</li><li>The OMMT library and piano roll should appear.</li></ol><p>If nothing opens, find OMMT in Minecraft’s key bindings. Change the editor key if another mod uses it.</p>`],
['folders','ファイルを置く場所',`<p>起動したプロファイルのゲームフォルダーに、次のフォルダーが作られます。ランチャーの別プロファイルへ入れないよう注意してください。</p><table><thead><tr><th>種類</th><th>場所</th></tr></thead><tbody><tr><td>MIDI（.mid / .midi）</td><td><code>OMMT/midi</code></td></tr><tr><td>Note Block Studio（.nbs）</td><td><code>OMMT/nbs</code></td></tr><tr><td>編集の保存（.ommt）</td><td><code>OMMT/saves</code></td></tr></tbody></table><p>ライブラリの「MIDI」「NBS」「保存」を切り替えると、対応する場所が表示されます。「フォルダーを開く」で場所を開き、ファイルを入れたら「更新」を押してください。</p>`,
'Where files go',`<p>OMMT creates these folders inside the game directory of the profile you launch. A different launcher profile has a different directory.</p><table><thead><tr><th>File type</th><th>Folder</th></tr></thead><tbody><tr><td>MIDI (.mid / .midi)</td><td><code>OMMT/midi</code></td></tr><tr><td>Note Block Studio (.nbs)</td><td><code>OMMT/nbs</code></td></tr><tr><td>Saved project (.ommt)</td><td><code>OMMT/saves</code></td></tr></tbody></table><p>Select MIDI, NBS, or SAVE in the library. Use “OPEN FOLDER”, add your file, and press “REFRESH”.</p>`]
]);

page('first-song','start','最初の1曲を送る','Send your first song','まずは短い曲で、読み込みから送信までを一度試してみましょう。','Start with a short song and follow the complete import-to-upload workflow.',[
['import','1. 曲を読み込む',`<ol><li>MIDIなら<code>OMMT/midi</code>、NBSなら<code>OMMT/nbs</code>へファイルを入れます。</li><li>ライブラリの対応するタブで「更新」を押します。</li><li>ファイルをダブルクリックします。1回クリックで選んでから、上部の「MIDI読込」「NBS読込」を押しても開けます。</li></ol><p>ピアノロールに並ぶ横長の棒が、1つずつの音（ノート）です。横が時間、縦が音の高さを表します。</p>`,
'1. Import a song',`<ol><li>Put MIDI files in <code>OMMT/midi</code> or NBS files in <code>OMMT/nbs</code>.</li><li>Choose the matching library tab and press “REFRESH”.</li><li>Double-click the file, or select it and press “LOAD MIDI” / “LOAD NBS”.</li></ol><p>Each horizontal bar in the piano roll is one note. Time runs left to right; higher notes appear higher on the screen.</p>`],
['listen','2. 聞いて、画面を合わせる',`<p><kbd>Space</kbd>で試聴を始め、もう一度押すと一時停止します。<kbd>Home</kbd>で先頭へ戻れます。</p><p>ノートが画面に収まらないときは「全体表示」（<kbd>F</kbd>）を押します。再生位置へ画面を追いかけさせたくないときは「追従」をOFFにしてください。</p><p>元の曲と楽器の印象が違っても、すぐに全音を変える必要はありません。まず主旋律がどのパートかを聞き分けます。</p>`,
'2. Listen and adjust the view',`<p>Press <kbd>Space</kbd> to play or pause, and <kbd>Home</kbd> to return to the start. “FIT” (<kbd>F</kbd>) fits the song’s time and pitch range into view.</p><p>Turn FOLLOW off if you want the view to stay still during playback. Listen for the melody before changing every instrument; a Minecraft arrangement will not necessarily sound like the original synthesizer.</p>`],
['edit','3. 1音だけ編集する',`<ol><li>気になるノートを左クリックして選びます。</li><li>右側の「ノートインスペクター」で音量を少し下げます。</li><li>「適用」を押し、前後を試聴します。</li><li>戻したいときは<kbd>Ctrl</kbd> + <kbd>Z</kbd>を押します。</li></ol><p>最初は1音で操作を試すと、変更範囲を見失いません。まとめて編集する方法は<a href="editing.html">ノート編集</a>で説明します。</p>`,
'3. Make one small edit',`<ol><li>Click a note to select it.</li><li>Lower its volume a little in NOTE INSPECTOR.</li><li>Press “APPLY” and listen to the surrounding phrase.</li><li>Use <kbd>Ctrl</kbd> + <kbd>Z</kbd> to undo if needed.</li></ol><p>Start with one note so the scope of the change is clear. See <a href="editing-en.html">note editing</a> when you are ready to edit a selection.</p>`],
['save','4. 編集を保存する',`<p>上部の曲名を分かりやすくし、「編集を保存」を押します。<code>OMMT/saves</code>に<code>.ommt</code>ができ、ライブラリの「保存」から再開できます。</p><aside class="note"><strong>元のMIDI・NBSは編集内容で上書きされません。</strong><p>続きを残すには「編集を保存」が必要です。サーバーへの送信とは別の操作です。</p></aside>`,
'4. Save your edit',`<p>Give the song a useful name and press “SAVE PROJECT”. A <code>.ommt</code> file is saved in <code>OMMT/saves</code>. Open it from the SAVE library tab to resume.</p><aside class="note"><strong>Your original MIDI or NBS file is not overwritten.</strong><p>Save a project to keep your changes. Saving locally and uploading are separate actions.</p></aside>`],
['send','5. おやさいサーバーへ送る',`<ol><li>おやさいサーバーへ接続します。</li><li>OMMTで保存した編集データを開き、曲名と内容を確認します。</li><li>「下書き送信」を押し、完了表示を待ちます。</li></ol><p>送信されるのは<strong>非公開の下書き</strong>です。送っただけで全員に公開・再生されるわけではありません。以降の曲管理はサーバーのOyasaiMusicで行います。</p><p>失敗した場合は連打せず、表示されたエラーを確認して<a href="help.html#upload">送信できないとき</a>へ進んでください。</p>`,
'5. Upload to the Oyasai Server',`<ol><li>Connect to the Oyasai Server.</li><li>Open your saved edit in OMMT and check the title and contents.</li><li>Press “UPLOAD DRAFT” and wait for completion.</li></ol><p>This creates a <strong>private draft</strong>, not a public release or a broadcast to everyone. Manage the uploaded song through OyasaiMusic on the server.</p><p>If upload fails, read the error before trying again. See <a href="help-en.html#upload">upload troubleshooting</a>.</p>`]
]);

page('editing','edit','ノートの選択と編集','Select and edit notes','選んでから変更するのが基本です。複数音を扱う前に、選択音数を確認します。','Select first, then edit. Check the selection count before changing several notes.',[
['view','画面の見方と移動',`<p>ピアノロールは横が時間、縦が音高です。ノートの横幅が長さ、色が所属パートを表します。上の数字は小節の位置です。</p><table><thead><tr><th>したいこと</th><th>初期設定の操作</th></tr></thead><tbody><tr><td>上下へ移動</td><td>ホイール</td></tr><tr><td>左右へ移動</td><td>Shift + ホイール</td></tr><tr><td>時間方向を拡大・縮小</td><td>Ctrl + ホイール</td></tr><tr><td>音高方向を拡大・縮小</td><td>Alt + ホイール</td></tr><tr><td>画面をつかんで移動</td><td>右ドラッグ</td></tr><tr><td>曲全体を収める</td><td>F</td></tr></tbody></table>`,
'Read and move around the piano roll',`<p>Horizontal position is time; vertical position is pitch. A note’s width shows its duration, and its color identifies its part. Numbers above the roll mark bars.</p><table><thead><tr><th>Action</th><th>Default input</th></tr></thead><tbody><tr><td>Move vertically</td><td>Wheel</td></tr><tr><td>Move along the timeline</td><td>Shift + wheel</td></tr><tr><td>Zoom time</td><td>Ctrl + wheel</td></tr><tr><td>Zoom pitch</td><td>Alt + wheel</td></tr><tr><td>Pan the view</td><td>Right drag</td></tr><tr><td>Fit the song</td><td>F</td></tr></tbody></table>`],
['notes','選択・移動・長さの変更',`<ul><li><strong>左クリック：</strong>1音を選択します。クリックしただけでは位置を変えません。</li><li><strong>Ctrl + ノートを左クリック：</strong>選択を追加・切り替えます。</li><li><strong>Shift + ドラッグ：</strong>範囲で選択します。</li><li><strong>選択音をドラッグ：</strong>時間と音高を動かします。</li><li><strong>ノート端をドラッグ：</strong>長さを変えます。</li><li><strong>Ctrl + 空白を左クリック：</strong>新しいノートを追加します。</li></ul><p>表示中の対象をまとめて選ぶには<kbd>Ctrl</kbd> + <kbd>A</kbd>。削除は<kbd>Delete</kbd>、取り消しは<kbd>Ctrl</kbd> + <kbd>Z</kbd>です。</p>`,
'Select, move, and resize',`<ul><li><strong>Click:</strong> select a note without moving it.</li><li><strong>Ctrl + click a note:</strong> add to or toggle the selection.</li><li><strong>Shift + drag:</strong> select a rectangular region.</li><li><strong>Drag selected notes:</strong> change their time and pitch.</li><li><strong>Drag a note edge:</strong> change its duration.</li><li><strong>Ctrl + click empty space:</strong> add a note.</li></ul><p><kbd>Ctrl</kbd> + <kbd>A</kbd> selects notes in the current view. <kbd>Delete</kbd> removes the selection; <kbd>Ctrl</kbd> + <kbd>Z</kbd> undoes an edit.</p>`],
['snap','スナップで位置を揃える',`<p>スナップは、移動や伸縮をリズムの目盛りに合わせる機能です。「スナップ」または<kbd>S</kbd>で<code>1/4 → 1/8 → 1/16 → 1/32 → 1/64 → OFF</code>と切り替えます。</p><p>まずは1/16で試し、細かい装飾音なら1/32や1/64へ変えてください。元の演奏のわずかなずれを残したい場合は、必要な部分だけOFFで調整します。画面を拡大しただけではスナップ設定は変わりません。</p>`,
'Align notes with snap',`<p>Snap aligns moves and resizes to a rhythmic grid. The SNAP button or <kbd>S</kbd> cycles through <code>1/4 → 1/8 → 1/16 → 1/32 → 1/64 → OFF</code>.</p><p>Try 1/16 first, and use 1/32 or 1/64 for finer ornaments. Turn snap off only where you want free timing. Zooming the view does not change the snap setting.</p>`],
['inspector','数値で編集する',`<p>ノートインスペクターの開始はミリ秒です。長さはミリ秒と1/1〜1/64の音価を切り替えられます。音高の<code>-12 / -1 / +1 / +12</code>は、それぞれ1オクターブ・半音の移動です。</p><p>数値を入力したら「適用」で確定します。複数選択の音高・音量・定位は代表音からの変化量で編集するため、元の音同士の差を保った調整ができます。ただし上限・下限に達すると値は収まる範囲に制限されます。</p><h3>例：主旋律を1オクターブ上げる</h3><ol><li>主旋律のパートを表示します。</li><li>上げたい音を範囲選択します。</li><li>音高の「+12」で上げ、試聴します。</li></ol><p>音のまとまりを整理したいときは<a href="parts.html">パート編集</a>へ進んでください。</p>`,
'Edit precise values',`<p>Start time uses milliseconds. Duration can use milliseconds or note lengths from 1/1 to 1/64. Pitch buttons <code>-12 / -1 / +1 / +12</code> move by an octave or a semitone.</p><p>Confirm typed values with APPLY. Pitch, volume, and pan changes across a selection are relative to the representative note, preserving differences until a value reaches its allowed limit.</p><h3>Example: raise the melody by an octave</h3><ol><li>Open the melody part.</li><li>Select the phrase to change.</li><li>Use +12 and listen to the result.</li></ol><p>To reorganize groups of notes, see <a href="parts-en.html">parts</a>.</p>`]
]);

page('parts','edit','パートを整理する','Organize parts','主旋律・伴奏・ベースなど、後から選びやすい単位に曲を分けます。','Group notes into melody, accompaniment, bass, or any arrangement that is easy to revisit.',[
['view','全体表示とパート表示',`<p>「全体」はすべてのパートを確認する表示です。パートを選ぶと、そのパートを中心に編集できます。他パートの補助表示は設定で変えられます。</p><p>パートが多い曲では、楽器ごとの階層を開いてレイヤーを探します。元のMIDIのトラックやNBSのレイヤーを確認してから、必要なものに名前を付けると見失いにくくなります。同じ楽器だからという理由だけで元のパートが1つに統合されるわけではありません。</p>`,
'All parts or one part',`<p>ALL shows the arrangement across every part. Select a part to focus your editing on it. Other-part guide display can be changed in settings.</p><p>For songs with many parts, expand the instrument groups to find their layers. Identify the original MIDI tracks or NBS layers before renaming them. Parts are not merged merely because they use the same instrument.</p>`],
['create','新しいパートへ分ける',`<ol><li>分離したいノートを選択します。</li><li>ノートインスペクターの「選択音からパート作成」を押します。</li><li>新しいパートを確認し、「現在のパート名」を入力して「パート名を変更」を押します。</li></ol><p>例えばピアノの高音側を「主旋律」、残りを「伴奏」とすると、主旋律だけの音色変更や音量調整がしやすくなります。</p>`,
'Create a part from selected notes',`<ol><li>Select the notes to separate.</li><li>Press NEW PART FROM SELECTION in the inspector.</li><li>Check the new part, enter an Active part name, and press RENAME ACTIVE PART.</li></ol><p>For example, call a piano’s upper phrase “Melody” and the rest “Accompaniment”. You can then adjust the melody without affecting the accompaniment.</p>`],
['move','既存のパートへ移す',`<ol><li>移したいノートを選択します。</li><li>「選択音の移動先」で既存パートを選びます。</li><li>その上にある「既存パートへ移動」を押します。</li></ol><p>移動先のパートを開き、音数や配置を確認してください。パートの移動と楽器の変更は別の操作です。音色を揃える場合は、移動後に対象音を選んで<a href="sound.html">楽器を変更</a>します。</p>`,
'Move notes into an existing part',`<ol><li>Select the notes you want to move.</li><li>Choose the destination in Move selected to.</li><li>Press MOVE TO EXISTING PART above that field.</li></ol><p>Open the destination part and check the result. Part membership and instrument choice are separate: select the moved notes and <a href="sound-en.html">change their instrument</a> if you want a consistent sound.</p>`]
]);

page('sound','edit','楽器とサウンドを選ぶ','Choose instruments and sounds','変えるノートを選び、音色を指定して、前後のフレーズと一緒に聞き直します。','Select the notes to change, choose a sound, and listen to it in context.',[
['instrument','音符ブロックの楽器',`<ol><li>対象のノートを選択します。パート全体を変える場合は、そのパートを表示して全選択します。</li><li>ノートインスペクターの「楽器」から音色を選びます。</li><li>「適用」を押して試聴します。</li></ol><p>楽器名の横には対応するブロック系統も表示されます。26.2ではラッパ系4種も使用できます。NBSから読み込んだラッパを使う場合は、対応したOMMTとサーバープラグインであることも確認してください。</p><p>MIDIの楽器はMinecraft向けに置き換わります。原曲の音源そのものを再現する機能ではないので、旋律が聞き取りやすい楽器を選び直して構いません。</p>`,
'Note block instruments',`<ol><li>Select the notes. To change a whole part, show that part and select all.</li><li>Choose an instrument in NOTE INSPECTOR.</li><li>Press APPLY and listen.</li></ol><p>The list includes the corresponding block family. The 26.2 target supports four trumpet variants; imported NBS trumpets also need a compatible server plugin.</p><p>MIDI instruments are mapped to Minecraft instruments, not to the original synthesizer samples. Choose a different instrument if it makes the melody clearer.</p>`],
['custom','その他のMinecraftサウンド',`<p>「その他のMinecraftサウンド」を選ぶと、検索欄・サウンド一覧・固定パターンが表示されます。</p><ol><li><code>bell</code>など、サウンドIDの一部で検索します。</li><li>候補から使うサウンドを選びます。</li><li>複数パターンがある場合は、使いたいパターンを指定します。</li><li>適用して試聴します。</li></ol><p>「同じIDの違う鳴り方」を選ぶのが固定パターンです。楽器や音高とは別の設定です。NBSのカスタム音源すべてが使えるわけではなく、対応するMinecraftサウンドに変換できない音は読み込み時の案内を確認してください。</p>`,
'Other Minecraft sounds',`<p>Select Other Minecraft sound to reveal the search field, event list, and fixed-pattern selector.</p><ol><li>Search for part of a sound ID, such as <code>bell</code>.</li><li>Choose an event from the results.</li><li>Select a fixed pattern when the event has several variants.</li><li>Apply and preview.</li></ol><p>A fixed pattern chooses a specific variation of the same event; it is separate from pitch. Not every NBS custom sample can be represented by a Minecraft sound. Read any conversion notices shown on import.</p>`],
['range','音域と拡張リソースパック',`<p>ピアノロールは元の音高を表示し、バニラ音域外の背景を区別します。背景が違うだけで、そのノートが消えたり壊れたりしているわけではありません。</p><p>拡張パックを使わない環境では、再生可能なバニラ音域へ収めて鳴らします。対応する拡張パックを読み込んだ環境では、対応音源を拡張音域で聞けます。OMMTを使うために拡張パックが必須というわけではありません。</p><p>おやさいサーバーでの許可・停止は<code>/mm rp allow</code> / <code>/mm rp deny</code>です。試聴とサーバー再生で音高の印象が違うときは、両方のパック適用状態を確認してください。</p>`,
'Pitch range and the optional resource pack',`<p>The piano roll keeps the source pitch visible and shades notes outside the vanilla range. Different shading does not mean a note is broken.</p><p>Without the extension pack, playback fits notes into the vanilla range. With a compatible loaded pack, supported sounds can use an extended range. The pack is not required to use OMMT.</p><p>On the Oyasai Server, use <code>/mm rp allow</code> or <code>/mm rp deny</code> to opt in or out. Check pack state when local preview and server playback sound different.</p>`]
]);

page('volume-pan','edit','音量と定位を整える','Balance volume and pan','主旋律が埋もれない音量に整えてから、必要に応じて左右の広がりを付けます。','Balance the melody and accompaniment first, then adjust the stereo position.',[
['volume','音量を変える',`<p>音量は0〜100です。ノートインスペクターへ数値を入れて適用する方法と、下の「音量」パネルで棒を上下へ動かす方法があります。0の音は試聴では鳴りません。</p><p>複数音を選んで相対的に調整できます。最初は1音の棒を動かして、ピアノロールの選択と対応を確かめてください。音が重なっていて選びにくい場合は時間方向を拡大します。</p><h3>例：伴奏が大きすぎる</h3><ol><li>伴奏パートを開いて対象音を選びます。</li><li>音量を少し下げて適用します。</li><li>全体表示に戻り、主旋律と一緒に試聴します。</li></ol>`,
'Adjust volume',`<p>Volume ranges from 0 to 100. Enter a value in the inspector and apply it, or drag a bar in the VOLUME panel. Zero-volume notes are silent in preview.</p><p>Selections can be adjusted relatively. Try one bar first to understand its connection to the selected note. Zoom in horizontally if overlapping bars are hard to target.</p><h3>Example: accompaniment is too loud</h3><ol><li>Open the accompaniment part and select its notes.</li><li>Lower the volume slightly and apply.</li><li>Return to ALL and listen with the melody.</li></ol>`],
['pan','定位で左右に振る',`<p>定位は<strong>-100が左、0が中央、+100が右</strong>です。ノートインスペクターまたは「定位」パネルで調整します。</p><p>左右に振り切る前に、伴奏の一部を-20、別の伴奏を+20程度から試してみてください。主旋律を中央に残すと、音の位置関係を比べやすくなります。これは調整例であり、曲に合わせて変えて構いません。</p>`,
'Place sounds left or right',`<p>Pan uses <strong>-100 for left, 0 for center, and +100 for right</strong>. Edit it in the inspector or the PAN panel.</p><p>As a starting experiment, try one accompaniment at -20 and another at +20 while leaving the melody centered. These are example values, not a rule; listen and adjust to suit your arrangement.</p>`],
['normalize','音量正規化との違い',`<p>上部の「音量正規化」は、曲全体の最大音量が100になるよう比率を保って音量を上げ下げします。特定のパートだけを聞きやすくする操作とは違います。</p><p>主旋律と伴奏のバランスを直したいときは、正規化を繰り返すのではなく、対象パートの音を選んで調整してください。</p>`,
'When to use MAX VOL',`<p>MAX VOL scales the whole song so its highest volume reaches 100 while preserving the ratio between notes. It is not a tool for balancing one part against another.</p><p>If the melody is buried, adjust the relevant part rather than repeatedly normalizing the entire song.</p>`]
]);

page('tempo','edit','曲の途中でテンポを変える','Change tempo during a song','テンポ点を置き、BPMと点の間の変わり方を決めます。','Place tempo points, set their BPM, and choose how the tempo changes between them.',[
['points','テンポ点を追加する',`<p>BPMは曲の速さです。曲の途中で変えたいときは、下部の「テンポ」パネルを使います。</p><ol><li>再生位置を変化させたい場所へ移します。</li><li>「再生位置に追加」を押します。</li><li>BPMと曲線を設定して「適用」を押します。</li><li>変化の前から再生して確認します。</li></ol><p>MIDIに元々テンポ変化がある場合は、読み込まれた点を先に確認してください。点を増やす前に、既存の点を編集できないかを見ます。</p>`,
'Add a tempo point',`<p>BPM describes the song’s speed. Use the TEMPO panel for changes within the song.</p><ol><li>Move the playhead to the intended position.</li><li>Press ADD AT PLAYHEAD.</li><li>Set BPM and the curve, then press APPLY.</li><li>Play from before the change to check it.</li></ol><p>Inspect imported tempo points before adding new ones. A MIDI file may already contain the change you want.</p>`],
['curves','曲線の選び方',`<table><thead><tr><th>曲線</th><th>聞こえ方の目安</th></tr></thead><tbody><tr><td>STEP</td><td>境目で速さを切り替える</td></tr><tr><td>LINEAR</td><td>直線的に速さを変える</td></tr><tr><td>SMOOTH</td><td>滑らかに速さを変える</td></tr></tbody></table><p>グラフのつながりを見て、意図した区間に曲線が付いているか確認してください。設定後は必ずその区間を試聴します。</p>`,
'Choose a curve',`<table><thead><tr><th>Curve</th><th>Purpose</th></tr></thead><tbody><tr><td>STEP</td><td>Switch tempo at a boundary</td></tr><tr><td>LINEAR</td><td>Change tempo along a straight slope</td></tr><tr><td>SMOOTH</td><td>Make a smooth transition</td></tr></tbody></table><p>Check the plotted line to confirm which interval you have changed, and always listen to that passage afterward.</p>`],
['example','例：最後のフレーズをゆっくりにする',`<ol><li>変化を始める位置と、遅くし終える位置に点を用意します。</li><li>最初を120 BPM、後を100 BPMにします。</li><li>その間がLINEARまたはSMOOTHでつながるように設定します。</li><li>遅くなる前の数小節から試聴し、速さと変化の長さを調整します。</li></ol><p>一瞬で速さが変わる場合は、曲線がSTEPになっていないか、点同士が近すぎないかを確認します。</p>`,
'Example: slow down the ending',`<ol><li>Place a point where the slowdown starts and another where it ends.</li><li>Set the first to 120 BPM and the second to 100 BPM.</li><li>Use a LINEAR or SMOOTH connection for the interval.</li><li>Listen from a few bars earlier and adjust the speed and transition length.</li></ol><p>If the change feels instantaneous, check for a STEP curve or points placed too close together.</p>`]
]);

page('release','edit','長い音に疑似リリースを付ける','Add pseudo-release to long notes','音を繰り返し鳴らしながら音量を変え、減衰や盛り上がりを作ります。','Retrigger a note while changing its volume to create a fade or swell.',[
['meaning','音をそのまま引き伸ばす機能ではありません',`<p>疑似リリースは、長いノートの途中で同じ音を一定間隔で鳴らし直す機能です。サンプル音そのものを長くするわけではないため、楽器や間隔によっては連打が聞こえます。</p><p>適用するのは<strong>選択音だけ</strong>です。まず長い1音で試し、効果を確認してから範囲を広げてください。</p>`,
'Retriggering, not stretching',`<p>Pseudo-release repeats a sound at intervals during a long note. It does not stretch the original sample, so repeated attacks may be audible depending on the instrument and interval.</p><p>It applies to <strong>selected notes only</strong>. Test one long note before applying it to a phrase.</p>`],
['controls','設定する項目',`<table><thead><tr><th>項目</th><th>意味</th></tr></thead><tbody><tr><td>連打判定</td><td>繰り返しの対象にするノートの長さ。ミリ秒または1/1〜1/64</td></tr><tr><td>連打間隔</td><td>次の音を鳴らすまでの間隔。ミリ秒または1/1〜1/128</td></tr><tr><td>開始・終了音量</td><td>ノートの元音量に対する割合（0〜100%）</td></tr><tr><td>曲線・中間点</td><td>音量の推移。中間点は最大2つで、上下左右へ動かせる</td></tr></tbody></table><p>音価を使うと曲の拍に沿った指定になります。固定の時間で繰り返したい場合はミリ秒を選びます。</p>`,
'Controls',`<table><thead><tr><th>Control</th><th>Meaning</th></tr></thead><tbody><tr><td>Threshold</td><td>Note length that qualifies for retriggering; milliseconds or 1/1–1/64</td></tr><tr><td>Interval</td><td>Time between retriggers; milliseconds or 1/1–1/128</td></tr><tr><td>Start / end volume</td><td>Percentage of the original note volume, from 0 to 100%</td></tr><tr><td>Curve / middle points</td><td>Volume envelope; up to two middle points, movable horizontally and vertically</td></tr></tbody></table><p>Use note lengths for beat-based timing, or milliseconds for a fixed time interval.</p>`],
['example','1音で試す',`<ol><li>長いノートを1音選び、「リリース」を開きます。</li><li>有効にし、連打判定をそのノートより短く設定します。</li><li>例として間隔を1/16、開始100%、終了30%、曲線SMOOTHにします。</li><li>「適用」を押して聞きます。連打が目立つ場合は間隔や楽器を変えます。</li></ol><p>この数値は調整を始める例です。短いノートや打楽器など、疑似リリースが合わない音もあります。不要になったら対象音を選び、「選択音から解除」を押してください。</p>`,
'Try it on one note',`<ol><li>Select a long note and open RELEASE.</li><li>Enable it and set the threshold below that note’s duration.</li><li>Try a 1/16 interval, 100% start, 30% end, and SMOOTH curve.</li><li>Press APPLY and listen. Adjust the interval or instrument if repeated attacks are too prominent.</li></ol><p>These values are a starting example. Short notes and some percussion may not benefit. Select the affected notes and use CLEAR SELECTED to remove the effect.</p>`]
]);

page('save-upload','reference','保存・再開・下書き送信','Save, resume, and upload','手元に編集を残す「保存」と、サーバーへ渡す「送信」を使い分けます。','Saving keeps an editable local project; uploading sends a draft to the server.',[
['save','編集を保存する',`<p>上部の「編集を保存」で、曲名をもとに<code>OMMT/saves</code>へ<code>.ommt</code>を保存します。保存するには1音以上のノートが必要です。完了表示を確認してから画面を閉じてください。</p><p>元のMIDI・NBSに編集内容は書き戻されません。別案も残したい場合は、保存先のファイルを複製してバックアップしてから作業します。</p><table><thead><tr><th>操作</th><th>残るもの</th></tr></thead><tbody><tr><td>編集を保存</td><td>手元の編集用 .ommt</td></tr><tr><td>試聴</td><td>保存・送信は行わない</td></tr><tr><td>下書き送信</td><td>サーバーの非公開下書き</td></tr></tbody></table>`,
'Save a project',`<p>SAVE PROJECT writes a <code>.ommt</code> file based on the song title into <code>OMMT/saves</code>. At least one note is required. Wait for the success message before closing.</p><p>The original MIDI or NBS is not updated. Duplicate the saved file as a backup before trying an alternative arrangement.</p><table><thead><tr><th>Action</th><th>Result</th></tr></thead><tbody><tr><td>SAVE PROJECT</td><td>An editable local .ommt project</td></tr><tr><td>Preview</td><td>No save or upload</td></tr><tr><td>UPLOAD DRAFT</td><td>A private server draft</td></tr></tbody></table>`],
['resume','続きを開く',`<ol><li>ライブラリの「保存」タブへ切り替えます。</li><li>保存ファイルをダブルクリックするか、選択して上部の「保存読込」を押します。</li><li>曲名・パート・編集内容が期待したものか確認します。</li></ol><p>元のMIDIやNBSを開き直すと、元ファイルからの読み込みになります。前回の編集を続けるときは「保存」タブを使ってください。</p>`,
'Resume editing',`<ol><li>Switch the library to SAVE.</li><li>Double-click the project, or select it and press LOAD SAVE.</li><li>Check the title, parts, and edits before continuing.</li></ol><p>Loading the original MIDI or NBS imports the source again. Use SAVE to resume your previous work.</p>`],
['upload','送信前と送信後',`<ul><li>おやさいサーバーへ接続しているか</li><li>曲名が正しいか</li><li>曲の先頭・中間・終わりを試聴したか</li><li>不要な音や極端な音量が残っていないか</li><li>手元の .ommt を保存したか</li></ul><p>確認できたら「下書き送信」を押し、完了を待ちます。送信中に何度も押したり切断したりせず、失敗したら表示内容を確認してください。</p><p>送信成功は<strong>公開の完了ではありません</strong>。作成された非公開下書きの管理は、サーバーのOyasaiMusicで行います。サーバーで受け付けられない内容や権限不足の場合は、送信に失敗することがあります。</p>`,
'Before and after uploading',`<ul><li>Connect to the Oyasai Server.</li><li>Check the song title.</li><li>Listen to the beginning, middle, and ending.</li><li>Remove unwanted notes and check extreme volume changes.</li><li>Keep a local .ommt save.</li></ul><p>Press UPLOAD DRAFT once and wait. Avoid disconnecting or repeatedly pressing the button. Read any error before retrying.</p><p>Successful upload does <strong>not</strong> publish your song. Manage the private draft in the server’s OyasaiMusic interface. Unsupported content or missing permission can prevent an upload.</p>`]
]);

page('settings','reference','画面と操作を自分に合わせる','Customize the editor','配色・パネル配置・キー操作を調整します。編集データの保存とは別の設定です。','Adjust colors, panel layout, and controls. These settings are separate from your song project.',[
['general','設定を開く',`<p>上部の「設定」または<kbd>Ctrl</kbd> + <kbd>,</kbd>で開きます。閉じるときは設定ウィンドウ右上の×を使います。</p><p>表示倍率や補助表示を変えたら、ノートと文字が読みやすいか確かめます。Minecraftの言語が日本語ならOMMTも日本語、それ以外では英語表示です。</p>`,
'Open settings',`<p>Press SETTINGS or <kbd>Ctrl</kbd> + <kbd>,</kbd>. Close the settings window with its top-right ×.</p><p>After changing scale or guide visibility, check that note labels and controls remain readable. OMMT uses Japanese when Minecraft is set to Japanese, and English otherwise.</p>`],
['appearance','配色を変える',`<p>「配色」で基本スタイルを選び、色やサイズの項目を調整します。文字・背景・選択色などの変更は画面へ反映されるため、別のプレビューを開く必要はありません。</p><p>最初は背景と文字の明るさだけを変えてみてください。選択音とパートの色が近すぎると選択範囲を見失いやすくなります。変更をやり直したい場合は「基本スタイルへ戻す」を使います。</p>`,
'Change colors',`<p>In Appearance, choose a base style and adjust color and size controls. Changes are reflected in the editor itself; no separate preview is needed.</p><p>Start with background and text brightness. Keep selection colors distinct from part colors. Use the reset-to-base-style control if you want to start over.</p>`],
['layout','パネルの位置を変える',`<p>ライブラリ、ピアノロール、インスペクター、音量などのパネルは、タイトル部分から移動・ドッキングできます。画面幅に合わせて境界を調整し、使う項目が見切れない幅を確保します。</p><p>例えば音量をよく触るなら下部を広くし、ノートの数値編集が多いならインスペクターを広くします。崩れて戻せなくなった場合は、設定のレイアウト初期化を使います。</p>`,
'Arrange panels',`<p>Move and dock panels using their title areas. Resize boundaries to give the library, piano roll, inspector, and control panels enough room.</p><p>Enlarge the lower volume panel for mixing, or the inspector for numeric editing. Use the layout reset in settings if the arrangement becomes difficult to restore.</p>`],
['keymap','キー・ホイールを変える',`<p>「キーマップ」で変更したい操作を選び、使うキーを割り当てます。ホイール単体とShift・Ctrl・Alt併用時の動作、選択やパンの操作もここで調整できます。</p><p>エディターを開くキーは、Minecraft側のキー割り当てで変更します。エディター内の操作と混同しないようにしてください。初期値は<a href="shortcuts.html">ショートカット一覧</a>にまとめています。</p>`,
'Change keys and wheel actions',`<p>Use Keymap to assign editor actions and configure wheel behavior with Shift, Ctrl, or Alt, as well as selection and pan gestures.</p><p>The key that opens OMMT is configured in Minecraft’s key bindings, not the editor keymap. See the <a href="shortcuts-en.html">shortcut reference</a> for defaults.</p>`],
['share','設定を共有する',`<p>「共有」から設定をエンコードしたテキストとして書き出し、別のプロファイルで取り込めます。配色や配置を合わせたいときに使います。</p><p>取り込む前に現在の設定も書き出して控えておくと、元へ戻しやすくなります。<strong>この共有テキストに曲の編集内容を保存するわけではありません。</strong> 曲は .ommt で保存してください。</p>`,
'Share settings',`<p>Export an encoded settings string from Sharing and import it in another profile to reuse your setup.</p><p>Export your current settings before importing someone else’s so you can restore them. <strong>This text is not a song save.</strong> Use .ommt projects for your music.</p>`]
]);

page('shortcuts','reference','ショートカット一覧','Keyboard and mouse reference','初期設定の一覧です。操作が違う場合は、設定のキーマップを確認してください。','Default controls. If yours behave differently, check the editor keymap.',[
['playback','再生と表示',`<table><thead><tr><th>操作</th><th>キー</th></tr></thead><tbody><tr><td>再生・一時停止</td><td>Space</td></tr><tr><td>先頭へ</td><td>Home</td></tr><tr><td>曲全体を収める</td><td>F</td></tr><tr><td>追従を切り替える</td><td>L</td></tr><tr><td>スナップを切り替える</td><td>S</td></tr><tr><td>前・次のパート</td><td>[ / ]</td></tr><tr><td>全パート表示</td><td>バックスラッシュ（\\）</td></tr><tr><td>選択音を試聴</td><td>P</td></tr></tbody></table>`,
'Playback and view',`<table><thead><tr><th>Action</th><th>Key</th></tr></thead><tbody><tr><td>Play / pause</td><td>Space</td></tr><tr><td>Return to start</td><td>Home</td></tr><tr><td>Fit song</td><td>F</td></tr><tr><td>Toggle follow</td><td>L</td></tr><tr><td>Cycle snap</td><td>S</td></tr><tr><td>Previous / next part</td><td>[ / ]</td></tr><tr><td>All parts</td><td>Backslash (\\)</td></tr><tr><td>Preview selection</td><td>P</td></tr></tbody></table>`],
['edit','編集と設定',`<table><thead><tr><th>操作</th><th>キー</th></tr></thead><tbody><tr><td>コピー・切り取り・貼り付け</td><td>Ctrl + C / X / V</td></tr><tr><td>複製</td><td>Ctrl + D</td></tr><tr><td>元に戻す・やり直し</td><td>Ctrl + Z / Y</td></tr><tr><td>削除</td><td>Delete</td></tr><tr><td>表示中を全選択</td><td>Ctrl + A</td></tr><tr><td>時間の拡大・縮小</td><td>Ctrl + = / -</td></tr><tr><td>設定</td><td>Ctrl + ,</td></tr><tr><td>確定・適用</td><td>Enter</td></tr></tbody></table><p>文字入力中は入力欄の操作が優先される場合があります。ショートカットを試す前に、入力を確定してピアノロールへ戻ってください。</p>`,
'Editing and settings',`<table><thead><tr><th>Action</th><th>Key</th></tr></thead><tbody><tr><td>Copy / cut / paste</td><td>Ctrl + C / X / V</td></tr><tr><td>Duplicate</td><td>Ctrl + D</td></tr><tr><td>Undo / redo</td><td>Ctrl + Z / Y</td></tr><tr><td>Delete</td><td>Delete</td></tr><tr><td>Select all in view</td><td>Ctrl + A</td></tr><tr><td>Zoom time in / out</td><td>Ctrl + = / -</td></tr><tr><td>Settings</td><td>Ctrl + ,</td></tr><tr><td>Confirm / apply</td><td>Enter</td></tr></tbody></table><p>Text fields may take priority while typing. Finish text entry and return focus to the piano roll before using editing shortcuts.</p>`],
['mouse','マウス操作',`<p>選択・追加・範囲選択・移動・伸縮とホイールの一覧は<a href="editing.html#notes">ノート編集</a>を参照してください。</p><p>このWikiでは<kbd>/</kbd>で検索欄へ移動し、検索中の<kbd>Esc</kbd>で閉じられます。これはゲーム内ショートカットではありません。</p>`,
'Mouse controls',`<p>See <a href="editing-en.html#notes">note editing</a> for selection, creation, dragging, resizing, and wheel controls.</p><p>In this handbook, <kbd>/</kbd> opens search and <kbd>Esc</kbd> closes it. Those are website controls, not in-game shortcuts.</p>`]
]);

page('glossary','reference','用語集','Glossary','画面や説明で使う言葉を、操作と結び付けて確認できます。','A short reference for terms used in the editor and this handbook.',[
['notes','ノート・パート・レイヤー',`<dl><dt>ノート</dt><dd>1つの音。音高・開始位置・長さ・音量などを持ち、ピアノロールの棒として表示されます。</dd><dt>パート</dt><dd>OMMTでノートをまとめる単位。主旋律だけを選ぶなどの編集に使います。</dd><dt>レイヤー / トラック</dt><dd>NBS / MIDIの元ファイルにある音の分け方。読み込んだ後はOMMTのパートとして整理できます。</dd></dl>`,
'Notes, parts, and layers',`<dl><dt>Note</dt><dd>One sound with a pitch, start time, duration, volume, and other properties. Shown as a bar in the piano roll.</dd><dt>Part</dt><dd>A group of notes in OMMT, useful for editing one role such as the melody.</dd><dt>Layer / track</dt><dd>A grouping in an NBS / MIDI source file. After import, you can organize these notes into OMMT parts.</dd></dl>`],
['timing','小節・BPM・スナップ',`<dl><dt>小節</dt><dd>曲の位置を拍のまとまりで表す区切り。ピアノロール上部の番号で場所を確認します。</dd><dt>BPM / テンポ</dt><dd>演奏の速さ。BPMが大きいほど速くなります。</dd><dt>スナップ</dt><dd>ノートの移動や伸縮をリズムの目盛りに合わせる機能。</dd><dt>再生位置 / シーク</dt><dd>今から再生する場所と、その場所を移す操作。</dd></dl>`,
'Bars, BPM, and snap',`<dl><dt>Bar / measure</dt><dd>A group of beats used to locate a passage, numbered above the piano roll.</dd><dt>BPM / tempo</dt><dd>Playback speed. A higher BPM is faster.</dd><dt>Snap</dt><dd>Aligns note moves and resizes to rhythmic divisions.</dd><dt>Playhead / seek</dt><dd>The current playback position, and the action of moving to a different position.</dd></dl>`],
['sound','定位・音域・オートメーション',`<dl><dt>定位 / Pan</dt><dd>音の左右の位置。0が中央です。</dd><dt>音域</dt><dd>出せる音の高さの範囲。OMMTの表示する元音高と、環境ごとに実際に鳴る高さは異なる場合があります。</dd><dt>オートメーション</dt><dd>音量やテンポなどを図で編集する仕組み。OMMTでは音量・定位・テンポ・リリースを別パネルで操作します。</dd><dt>セント / デチューン</dt><dd>音高の細かいずれ。100セントで半音です。</dd></dl>`,
'Pan, range, and automation',`<dl><dt>Pan</dt><dd>The left-to-right position of a sound; 0 is centered.</dd><dt>Pitch range</dt><dd>The range of playable pitches. A displayed source pitch may sound different when playback is fitted to vanilla range.</dd><dt>Automation</dt><dd>Graphical editing of properties such as volume or tempo. OMMT has separate volume, pan, tempo, and release panels.</dd><dt>Cents / detune</dt><dd>Fine pitch offset. 100 cents equals one semitone.</dd></dl>`]
]);

page('help','reference','困ったとき','Troubleshooting','症状に近い項目から順に確認してください。直らないときは、状況を添えて報告できます。','Find the closest symptom below. If it persists, report the steps and relevant details.',[
['open','画面が開かない・ファイルが見つからない',`<ul><li><strong>画面が開かない：</strong>Minecraft 26.2と前提MODを確認し、Minecraftのキー割り当てでOMMTの起動キーが重複していないか確認します。</li><li><strong>一覧にファイルがない：</strong>MIDI・NBS・保存のタブ、起動したプロファイルのフォルダー、拡張子を確認して「更新」を押します。</li><li><strong>フォルダーを開けない：</strong>ランチャーの機能でそのプロファイルのゲームフォルダーを開き、OMMT内のmidi / nbs / savesへ移動します。</li><li><strong>読み込めない：</strong>エラー文を控え、別の小さなファイルでも起きるか試します。元ファイルは消さずに残してください。</li></ul>`,
'Editor will not open or a file is missing',`<ul><li><strong>Editor will not open:</strong> check Minecraft 26.2, required mods, and conflicting Minecraft key bindings.</li><li><strong>File not listed:</strong> check the library tab, active launcher profile directory, and extension, then refresh.</li><li><strong>OPEN FOLDER fails:</strong> open the profile directory through your launcher and navigate to OMMT/midi, nbs, or saves.</li><li><strong>Import fails:</strong> record the error and try a small file to see whether the problem affects every import. Keep the original file.</li></ul>`],
['audio','音が出ない・音色や高さが違う',`<ol><li>Minecraft自体の音量と、ノートの音量が0になっていないか確認します。</li><li>短いノートを1音選び、試聴できるか確認します。</li><li>選択した楽器、その他のサウンドの固定パターン、拡張パックの適用状態を確認します。</li><li>NBS読込時に代替音源の案内が出ていなかったか確認します。</li></ol><p>ローカル試聴だけで起きるのか、サーバー再生でも起きるのかを分けて記録すると調査しやすくなります。</p>`,
'No sound, or unexpected sound or pitch',`<ol><li>Check Minecraft’s volume and whether the note volume is zero.</li><li>Select one short note and try previewing it.</li><li>Check the instrument, fixed sound pattern, and extension-pack state.</li><li>Look for fallback-sound notices from the NBS import.</li></ol><p>Record whether the issue happens in local preview, server playback, or both.</p>`],
['editing','選択・編集・表示が思いどおりにならない',`<ul><li><strong>1音しか変わらない：</strong>変更前に対象音を選択してください。パート全体を変えるなら、そのパートで全選択します。</li><li><strong>動かすと位置がずれる：</strong>スナップ設定を確認します。微調整が必要なら一時的にOFFにします。</li><li><strong>編集前に戻った：</strong>元のMIDI/NBSではなく「保存」タブの .ommt を開いているか確認します。</li><li><strong>パネルが見つからない：</strong>設定の表示項目とレイアウトを確認します。配置を初期化する前に、必要なら設定を共有テキストへ書き出してください。</li><li><strong>重い：</strong>パートを絞って表示し、細部を確認する場所へ拡大します。特定のファイルだけで起きるなら、そのファイルと症状を報告してください。</li></ul>`,
'Selection, edits, or layout behave unexpectedly',`<ul><li><strong>Only one note changes:</strong> select the intended notes first. Open a part and select all to edit the whole part.</li><li><strong>Dragging changes the timing:</strong> check snap; disable it temporarily for free timing.</li><li><strong>Edits seem lost:</strong> open the .ommt project from SAVE, not the original MIDI or NBS.</li><li><strong>A panel is missing:</strong> check visibility and layout settings. Export settings before resetting a layout you want to keep.</li><li><strong>The editor is slow:</strong> focus on one part and zoom into the passage. Report the file and symptoms if it only affects a particular song.</li></ul>`],
['upload','下書きを送信できない',`<p>おやさいサーバーに接続し、送信に必要な権限があることを確認します。完了前に切断した場合やエラーが出た場合は、成功したものとして扱わないでください。</p><p>まず編集を .ommt に保存し、画面のエラーを控えます。楽器・サウンドを変えた直後なら、変更箇所とOMMTのバージョンも記録してください。読み込み成功だけでは、サーバーがその内容を受け付けられると限りません。</p>`,
'Draft upload fails',`<p>Connect to the Oyasai Server and check that you have upload permission. A disconnect before completion or an error does not mean the upload succeeded.</p><p>Save a local .ommt project and record the error. If the problem started after changing a sound, include that change and your OMMT version in the report. Successful import does not guarantee the server can accept the result.</p>`],
['report','報告するときに添えるもの',`<ul><li>MinecraftとOMMTのバージョン</li><li>何をして、どうなるはずが、どうなったか</li><li>エラーが分かる画面と、発生時刻</li><li>特定ファイルの場合は、共有できる元ファイルまたは .ommt</li><li>音の問題なら、ローカル試聴かサーバー再生か、パックの有無</li></ul><p>報告先は<a href="https://discord.gg/rgKayZPW6X">Discordサーバー</a>の<strong>showcase内、OMMTについて話しているスレッド</strong>です。ログを添付する際は、個人情報や接続先情報など不要な情報が含まれていないか確認してください。</p>`,
'What to include in a report',`<ul><li>Minecraft and OMMT versions</li><li>Your steps, expected result, and actual result</li><li>A screenshot of the error and the time it happened</li><li>The source file or .ommt project, if you can share it</li><li>For audio issues: local preview or server playback, and whether the pack was loaded</li></ul><p>Report in the <strong>OMMT discussion thread inside showcase</strong> on the <a href="https://discord.gg/rgKayZPW6X">Discord server</a>. Remove unnecessary personal or connection details before sharing logs.</p>`]
]);
